[newneek]
title = "뉴닉 ─ 전체"
url = "https://newneek.co/"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_presidential-election]
title = "뉴닉 ─ 2022 대선"
url = "https://newneek.co/tag/2022-presidential-election"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_politics]
title = "뉴닉 ─ 정치"
url = "https://newneek.co/tag/politics"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_world]
title = "뉴닉 ─ 세계"
url = "https://newneek.co/tag/world"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_tech]
title = "뉴닉 ─ 테크"
url = "https://newneek.co/tag/tech"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_economy]
title = "뉴닉 ─ 경제"
url = "https://newneek.co/tag/economy"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_labor]
title = "뉴닉 ─ 노동"
url = "https://newneek.co/tag/labor"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_environment]
title = "뉴닉 ─ 환경"
url = "https://newneek.co/tag/environment"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_women]
title = "뉴닉 ─ 여성"
url = "https://newneek.co/tag/women"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_covid-19]
title = "뉴닉 ─ 코로나19"
url = "https://newneek.co/tag/covid-19"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"

[newneek_pizzastation]
title = "뉴닉 ─ 피자스테이션"
url = "https://newneek.co/tag/pizzastation"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"